AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Particle Argon Candle Lights Control System

Parameters:
  DomainName:
    Type: String
    Default: lights.jeremy.ninja
    Description: Domain name for the website
  HostedZoneId:
    Type: String
    Description: Route53 Hosted Zone ID for the domain
  CertificateArn:
    Type: String
    Description: ACM Certificate ARN for the custom domain

Globals:
  Function:
    Runtime: provided.al2
    Architectures:
      - x86_64
    Timeout: 30
    Environment:
      Variables:
        USERS_TABLE: !Ref UsersTable
        PATTERNS_TABLE: !Ref PatternsTable
        DEVICES_TABLE: !Ref DevicesTable
        SESSIONS_TABLE: !Ref SessionsTable
        DOMAIN_NAME: !Ref DomainName

Resources:
  # DynamoDB Tables
  UsersTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub ${AWS::StackName}-users
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: username
          AttributeType: S
      KeySchema:
        - AttributeName: username
          KeyType: HASH
      StreamSpecification:
        StreamViewType: NEW_AND_OLD_IMAGES

  PatternsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub ${AWS::StackName}-patterns
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: patternId
          AttributeType: S
        - AttributeName: userId
          AttributeType: S
      KeySchema:
        - AttributeName: patternId
          KeyType: HASH
      GlobalSecondaryIndexes:
        - IndexName: userId-index
          KeySchema:
            - AttributeName: userId
              KeyType: HASH
          Projection:
            ProjectionType: ALL

  DevicesTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub ${AWS::StackName}-devices
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: deviceId
          AttributeType: S
        - AttributeName: userId
          AttributeType: S
      KeySchema:
        - AttributeName: deviceId
          KeyType: HASH
      GlobalSecondaryIndexes:
        - IndexName: userId-index
          KeySchema:
            - AttributeName: userId
              KeyType: HASH
          Projection:
            ProjectionType: ALL

  SessionsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub ${AWS::StackName}-sessions
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: sessionId
          AttributeType: S
        - AttributeName: username
          AttributeType: S
      KeySchema:
        - AttributeName: sessionId
          KeyType: HASH
      GlobalSecondaryIndexes:
        - IndexName: username-index
          KeySchema:
            - AttributeName: username
              KeyType: HASH
          Projection:
            ProjectionType: ALL
      TimeToLiveSpecification:
        AttributeName: expiresAt
        Enabled: true

  # CloudWatch Log Groups with retention
  AuthFunctionLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub '/aws/lambda/${AWS::StackName}-AuthFunction'
      RetentionInDays: 7

  PatternsFunctionLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub '/aws/lambda/${AWS::StackName}-PatternsFunction'
      RetentionInDays: 7

  DevicesFunctionLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub '/aws/lambda/${AWS::StackName}-DevicesFunction'
      RetentionInDays: 7

  ParticleFunctionLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub '/aws/lambda/${AWS::StackName}-ParticleFunction'
      RetentionInDays: 7

  FrontendFunctionLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub '/aws/lambda/${AWS::StackName}-FrontendFunction'
      RetentionInDays: 7

  # Lambda Functions
  AuthFunction:
    DependsOn: AuthFunctionLogGroup
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: makefile
    Properties:
      CodeUri: backend/functions/auth/
      Handler: bootstrap
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref UsersTable
        - DynamoDBCrudPolicy:
            TableName: !Ref SessionsTable
      Events:
        Login:
          Type: Api
          Properties:
            RestApiId: !Ref WebsiteGateway
            Path: /api/auth/login
            Method: POST
        Register:
          Type: Api
          Properties:
            RestApiId: !Ref WebsiteGateway
            Path: /api/auth/register
            Method: POST
        Validate:
          Type: Api
          Properties:
            RestApiId: !Ref WebsiteGateway
            Path: /api/auth/validate
            Method: POST
        UpdateParticleSettings:
          Type: Api
          Properties:
            RestApiId: !Ref WebsiteGateway
            Path: /api/settings/particle
            Method: POST

  PatternsFunction:
    DependsOn: PatternsFunctionLogGroup
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: makefile
    Properties:
      CodeUri: backend/functions/patterns/
      Handler: bootstrap
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref PatternsTable
        - DynamoDBReadPolicy:
            TableName: !Ref UsersTable
        - DynamoDBReadPolicy:
            TableName: !Ref SessionsTable
      Events:
        List:
          Type: Api
          Properties:
            RestApiId: !Ref WebsiteGateway
            Path: /api/patterns
            Method: GET
        Create:
          Type: Api
          Properties:
            RestApiId: !Ref WebsiteGateway
            Path: /api/patterns
            Method: POST
        Get:
          Type: Api
          Properties:
            RestApiId: !Ref WebsiteGateway
            Path: /api/patterns/{patternId}
            Method: GET
        Update:
          Type: Api
          Properties:
            RestApiId: !Ref WebsiteGateway
            Path: /api/patterns/{patternId}
            Method: PUT
        Delete:
          Type: Api
          Properties:
            RestApiId: !Ref WebsiteGateway
            Path: /api/patterns/{patternId}
            Method: DELETE

  DevicesFunction:
    DependsOn: DevicesFunctionLogGroup
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: makefile
    Properties:
      CodeUri: backend/functions/devices/
      Handler: bootstrap
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref DevicesTable
        - DynamoDBReadPolicy:
            TableName: !Ref UsersTable
        - DynamoDBReadPolicy:
            TableName: !Ref PatternsTable
        - DynamoDBReadPolicy:
            TableName: !Ref SessionsTable
      Events:
        List:
          Type: Api
          Properties:
            RestApiId: !Ref WebsiteGateway
            Path: /api/devices
            Method: GET
        Register:
          Type: Api
          Properties:
            RestApiId: !Ref WebsiteGateway
            Path: /api/devices
            Method: POST
        Get:
          Type: Api
          Properties:
            RestApiId: !Ref WebsiteGateway
            Path: /api/devices/{deviceId}
            Method: GET
        Update:
          Type: Api
          Properties:
            RestApiId: !Ref WebsiteGateway
            Path: /api/devices/{deviceId}
            Method: PUT
        Delete:
          Type: Api
          Properties:
            RestApiId: !Ref WebsiteGateway
            Path: /api/devices/{deviceId}
            Method: DELETE
        AssignPattern:
          Type: Api
          Properties:
            RestApiId: !Ref WebsiteGateway
            Path: /api/devices/{deviceId}/pattern
            Method: PUT

  ParticleFunction:
    DependsOn: ParticleFunctionLogGroup
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: makefile
    Properties:
      CodeUri: backend/functions/particle/
      Handler: bootstrap
      Policies:
        - DynamoDBReadPolicy:
            TableName: !Ref DevicesTable
        - DynamoDBReadPolicy:
            TableName: !Ref PatternsTable
        - DynamoDBReadPolicy:
            TableName: !Ref UsersTable
        - DynamoDBReadPolicy:
            TableName: !Ref SessionsTable
      Events:
        SendCommand:
          Type: Api
          Properties:
            RestApiId: !Ref WebsiteGateway
            Path: /api/particle/command
            Method: POST
        GetDeviceInfo:
          Type: Api
          Properties:
            RestApiId: !Ref WebsiteGateway
            Path: /api/particle/device/{deviceId}
            Method: GET
        RefreshDevices:
          Type: Api
          Properties:
            RestApiId: !Ref WebsiteGateway
            Path: /api/particle/devices/refresh
            Method: POST
        ValidateToken:
          Type: Api
          Properties:
            RestApiId: !Ref WebsiteGateway
            Path: /api/particle/validate-token
            Method: POST
        OAuthInitiate:
          Type: Api
          Properties:
            RestApiId: !Ref WebsiteGateway
            Path: /api/particle/oauth/initiate
            Method: POST

  # Frontend Lambda (Go Fiber)
  FrontendFunction:
    DependsOn: FrontendFunctionLogGroup
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: makefile
    Properties:
      CodeUri: frontend/
      Handler: bootstrap
      MemorySize: 512
      Timeout: 30
      Environment:
        Variables:
          API_ENDPOINT: !Sub https://${DomainName}
      Policies:
        - Statement:
            - Effect: Allow
              Action:
                - dynamodb:GetItem
                - dynamodb:Query
              Resource:
                - !GetAtt UsersTable.Arn
                - !GetAtt SessionsTable.Arn
      Events:
        Root:
          Type: Api
          Properties:
            RestApiId: !Ref WebsiteGateway
            Path: /
            Method: ANY
        Proxy:
          Type: Api
          Properties:
            RestApiId: !Ref WebsiteGateway
            Path: /{proxy+}
            Method: ANY

  WebsiteGateway:
    Type: AWS::Serverless::Api
    Properties:
      Name: !Sub ${AWS::StackName}-website
      StageName: prod
      BinaryMediaTypes:
        - "image/*"
        - "application/octet-stream"
        - "application/pdf"
      Cors:
        AllowMethods: "'GET,POST,PUT,DELETE,OPTIONS'"
        AllowHeaders: "'Content-Type,Authorization,X-Amz-Date,X-Api-Key,X-Amz-Security-Token'"
        AllowOrigin: "'*'"
      Domain:
        DomainName: !Ref DomainName
        CertificateArn: !Ref CertificateArn
        EndpointConfiguration: REGIONAL
        Route53:
          HostedZoneId: !Ref HostedZoneId

Outputs:
  WebsiteUrl:
    Description: Website URL (API available at /api)
    Value: !Sub https://${DomainName}
  UsersTableName:
    Description: Users DynamoDB table name
    Value: !Ref UsersTable
  PatternsTableName:
    Description: Patterns DynamoDB table name
    Value: !Ref PatternsTable
  DevicesTableName:
    Description: Devices DynamoDB table name
    Value: !Ref DevicesTable
  SessionsTableName:
    Description: Sessions DynamoDB table name
    Value: !Ref SessionsTable
